baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'EMI Research Group'
staticDir = ['static']
ignoreLogs = ['warning-goldmark-raw-html']

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 2
    [minify.tdewolff.html]
      keepQuotes = false
      keepWhitespace = false

[menu]
  [[menu.main]]
    name = 'Research'
    pageRef = '/research'
    weight = 10

  [[menu.main]]
    name = 'People'
    pageRef = '/people'
    weight = 20

  [[menu.main]]
    name = 'Facilities'
    pageRef = '/facilities'
    weight = 25

  [[menu.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 30

  [[menu.main]]
    name = 'Positions'
    pageRef = '/positions'
    weight = 40
